const ActionTypes = {

    CITY_DATA_ERROR: 'CITY_DATA_ERROR', 
    CITY_DATA_IS_LOADING: 'CITY_DATA_IS_LOADING',
    CITY_DATA_FETCH_SUCCESS: 'CITY_DATA_FETCH_SUCCESS',

    TRAVELLER_DATA_ERROR: 'TRAVELLER_DATA_ERROR', 
    TRAVELLER_DATA_IS_LOADING: 'TRAVELLER_DATA_IS_LOADING',
    TRAVELLER_DATA_FETCH_SUCCESS: 'TRAVELLER_DATA_FETCH_SUCCESS',

    UPDATE_NEW_TRIP: 'UPDATE_NEW_TRIP',
    TOGGLE_ADD_TRIP: 'TOGGLE_ADD_TRIP',
    TRIP_DATA_ERROR: 'TRIP_DATA_ERROR', 
    TRIP_DATA_IS_LOADING: 'TRIP_DATA_IS_LOADING',
    TRIP_DATA_FETCH_SUCCESS: 'TRIP_DATA_FETCH_SUCCESS',
    SUBMIT_NEW_TRIP: 'SUBMIT_NEW_TRIP',
    NEW_TRIP_SUCCESS: 'NEW_TRIP_SUCCESS',
    NEW_TRIP_PENDING_CONFIRMATION: 'NEW_TRIP_PENDING_CONFIRMATION',
    NEW_TRIP_ERRORED: 'NEW_TRIP_ERRORED'

}

export default ActionTypes;